### PR TITLE
Forget balance subscribtion in page changes

### PR DESCRIPTION
**Pull request by morteza-binary**

### CODE REVIEW

**Comment by ashkanx** [comment]
**Balance** should be always available. why do we need to forget & call it again in page changes?

**Comment by morteza-binary** [comment]
You mean we have balance in all of pages?

**Comment by morteza-binary** [comment]
BTW, changes is essential since balance directive should be isolate, it has to forget all of subscriptions when it is destroyed.

**Comment by ashkanx** [comment]
Yes. We will have it in all pages

**Comment by ashkanx** [comment]
OK. Then I merge this

**Comment by morteza-binary** [comment]
So if it should be in all pages, we have to change the position of it and put in in share template

**Comment by morteza-binary** [comment]
Plz do it no, since Nazanin needs it.

**Comment by ashkanx** [comment]
done

**Comment by morteza-binary** [comment]
thanks

**Pull request merged**
